import type { ChangeRequest, ProjectArchive, SigningContract, SpaceAllocation, SpaceUsageLog } from './hatchTypes'

export const INITIAL_CONTRACTS: SigningContract[] = [
  {
    id: 'c-1',
    projectId: 'h-proj-1',
    projectName: '基因治疗项目',
    incubationType: '实体',
    signStatus: '已生效',
    contractEnd: '2026-05-10',
    rentYuanPerMonth: 5000,
    propertyFee: 500,
    techFeeYuanPerMonth: 0,
    aiPackage: '标准版（1000次/月）',
    spaceNeed: '空间 B301，设备流式细胞仪',
    templateId: 'tpl-1',
    templateName: '实体入孵协议 v2',
    termStart: '2025-05-10',
    termEnd: '2026-05-09',
    scanFileName: 'contract_scan.pdf',
    createdAt: '2025-05-10',
    crmContractId: 'crm-1001',
    remindLogs: [
      { id: 'rl-1', contractId: 'c-1', remindDay: 30, remindTime: '2025-04-10 09:00', method: '站内信+邮件', status: '成功' },
      { id: 'rl-2', contractId: 'c-1', remindDay: 15, remindTime: '2025-04-25 09:00', method: '站内信+邮件', status: '成功' },
    ],
  },
  {
    id: 'c-2',
    projectId: 'h-proj-2',
    projectName: 'AI 新药平台',
    incubationType: '虚拟',
    signStatus: '待签署',
    contractEnd: null,
    rentYuanPerMonth: 2000,
    propertyFee: 0,
    techFeeYuanPerMonth: 500,
    aiPackage: '轻量版（月费 300 元）',
    templateId: 'tpl-2',
    templateName: '虚拟入孵协议 v1',
    termStart: '2026-06-01',
    termEnd: '2027-05-31',
    createdAt: '2025-05-19',
  },
  {
    id: 'c-3',
    projectId: 'h-proj-3',
    projectName: '细胞治疗项目',
    incubationType: '实体',
    signStatus: '即将到期',
    contractEnd: '2025-06-01',
    rentYuanPerMonth: 5500,
    propertyFee: 550,
    techFeeYuanPerMonth: 0,
    templateId: 'tpl-1',
    templateName: '实体入孵协议 v2',
    termStart: '2024-06-01',
    termEnd: '2025-06-01',
    scanFileName: 'cell_signed.pdf',
    createdAt: '2024-06-01',
    crmContractId: 'crm-1003',
  },
  {
    id: 'c-4',
    projectId: 'h-proj-4',
    projectName: '抗体项目',
    incubationType: '服务商',
    signStatus: '已到期',
    contractEnd: '2024-12-31',
    rentYuanPerMonth: null,
    templateId: 'tpl-3',
    templateName: '服务商认证协议',
    termStart: '2023-01-01',
    termEnd: '2024-12-31',
    createdAt: '2023-01-05',
  },
]

export const INITIAL_ARCHIVES: ProjectArchive[] = [
  {
    id: 'h-proj-1',
    name: '基因治疗项目',
    entityType: '企业',
    incubationType: '实体',
    status: '正常运营',
    tags: ['高潜力', '细胞治疗', '临床前'],
    creditCode: '91110105MA01234XXX',
    address: '北京市海淀区中关村大街 1 号',
    contact: '周敏',
    phone: '138****1234',
    incubationStart: '2025-05-10',
    contractEnd: '2026-05-09',
    flowCurrent: 'operate',
    pipeline: [
      {
        id: 'p1',
        productName: '基因编辑药物',
        indication: '血友病',
        stage: '临床前',
        milestone: 'IND 筹备',
      },
    ],
    team: [{ id: 't1', name: '张建国', title: '创始人 / CEO', bio: '连续创业者' }],
    funding: [{ id: 'f1', round: 'A 轮', amount: '5000 万', investor: '红杉', date: '2025-03' }],
    resourceDemand: '空间：共享实验室；设备：流式细胞仪；专家：基因编辑方向',
    resourceSupply: '无',
    evaluations: [
      { id: 'e1', type: 'AI 初筛', score: '86', conclusion: '推荐实体入驻', time: '2025-05-10' },
      { id: 'e2', type: '专家评审', score: '88', conclusion: '推荐入驻', time: '2025-05-12' },
    ],
    events: [{ id: 'ev1', time: '2025-05-15', description: '完成入孵签约' }],
    changeHistory: [],
    spaceHistory: [
      { id: 'sh1', time: '2025-05-10', opType: '分配', roomName: 'B栋-3F-301', areaM2: 80, operator: 'admin' },
      { id: 'sh2', time: '2025-06-15', opType: '扩租', roomName: 'B栋-3F-302', areaM2: 50, operator: '李四' },
    ],
  },
  {
    id: 'h-proj-2',
    name: 'AI 新药平台',
    entityType: '高校',
    incubationType: '虚拟',
    status: '待签约',
    tags: ['AI 制药'],
    creditCode: '12100004XXXX56789X',
    address: '上海市杨浦区',
    contact: '李华',
    phone: '139****5678',
    incubationStart: null,
    contractEnd: null,
    flowCurrent: 'signing',
    pipeline: [],
    team: [],
    funding: [],
    resourceDemand: '算力与数据标注外包',
    resourceSupply: '高校实验室开放机时',
    evaluations: [{ id: 'e1', type: 'AI 初筛', score: '82', conclusion: '建议虚拟孵化', time: '2025-05-08' }],
    events: [],
    changeHistory: [],
  },
  {
    id: 'h-proj-3',
    name: '细胞治疗项目',
    entityType: '企业',
    incubationType: '实体',
    status: '正常运营',
    tags: ['细胞治疗', 'IND'],
    creditCode: '91310115MA98765YYY',
    address: '上海市浦东新区',
    contact: '王五',
    phone: '136****9012',
    incubationStart: '2024-06-01',
    contractEnd: '2025-06-01',
    flowCurrent: 'operate',
    pipeline: [],
    team: [],
    funding: [],
    resourceDemand: '临床 CRO 对接',
    resourceSupply: '无',
    evaluations: [],
    events: [],
    changeHistory: [],
    spaceHistory: [{ id: 'sh-c1', time: '2024-08-01', opType: '分配', roomName: 'B栋-2F-203', areaM2: 50, operator: 'admin' }],
  },
  {
    id: 'h-proj-4',
    name: '抗体项目',
    entityType: '企业',
    incubationType: '实体',
    status: '正常运营',
    tags: ['抗体', '扩租意向'],
    creditCode: '91440300MA112233XX',
    address: '深圳市南山区',
    contact: '赵六',
    phone: '135****3344',
    incubationStart: '2025-01-10',
    contractEnd: '2027-01-01',
    flowCurrent: 'operate',
    pipeline: [],
    team: [],
    funding: [],
    resourceDemand: '中试放大场地',
    resourceSupply: '无',
    evaluations: [],
    events: [],
    changeHistory: [],
    spaceHistory: [
      { id: 'sh-ab1', time: '2025-01-10', opType: '分配', roomName: 'A栋-1F-101', areaM2: 100, operator: 'admin' },
      { id: 'sh-ab2', time: '2025-03-01', opType: '扩租', roomName: 'A栋-1F-102', areaM2: 100, operator: '王运营' },
    ],
  },
]

export const INITIAL_SPACES: SpaceAllocation[] = [
  {
    id: 'sp-1',
    projectId: 'h-proj-1',
    projectName: '基因治疗项目',
    location: 'B 栋 301 室',
    areaM2: 80,
    assignDate: '2025-05-10',
    endDate: '2026-05-09',
    status: '正常',
  },
]

export const INITIAL_SPACE_LOGS: Record<string, SpaceUsageLog[]> = {
  'sp-1': [
    { id: 'sl1', time: '2025-05-10', type: '分配', areaDelta: '+80㎡', reason: '入孵分配', operator: 'admin' },
    { id: 'sl2', time: '2025-06-15', type: '扩租', areaDelta: '+30㎡', reason: '团队扩张', operator: '李四' },
  ],
}

export const INITIAL_CHANGES: ChangeRequest[] = [
  {
    id: 'chg-1',
    projectId: 'h-proj-2',
    projectName: 'AI 新药平台',
    changeType: '入孵类型变更',
    summary: '虚拟转实体',
    applicant: '张三',
    status: '待审批',
    detail: '目标类型：实体入孵',
  },
  {
    id: 'chg-2',
    projectId: 'h-proj-1',
    projectName: '基因治疗项目',
    changeType: '空间变更',
    summary: '扩租 30㎡',
    applicant: '李四',
    status: '已通过',
    detail: '扩租 B301 相邻区域',
  },
  {
    id: 'chg-3',
    projectId: 'h-proj-3',
    projectName: '细胞治疗项目',
    changeType: '退出/毕业',
    summary: '毕业申请',
    applicant: '王五',
    status: '待审批',
    reason: '产品已上市，营收达标',
    exitType: '毕业',
  },
]
