import type { ResApplication, ResResource, ResReview, ResUsageOrder } from './resopsV1Types'

export const DEMO_APPLICANT_KEYS = {
  gene: 'applicant_gene',
  aiDrug: 'applicant_ai',
} as const

export function initialResources(): ResResource[] {
  return [
    {
      id: 'res-flow',
      name: '流式细胞仪',
      level1: '资源共享',
      level2: '设备',
      providerName: '园区公共实验平台',
      status: 'listed',
      location: 'B301',
      intro: '高精度流式分析，支持多色面板。',
      hours: '周一至周五 9:00-17:00',
      contactName: '周工',
      phone: '021-12345678',
      capability: '可做细胞表面标记分析、凋亡检测等。',
      feeMode: 'hourly',
      priceAmount: 200,
      priceUnit: '元/小时',
      remark: '单次最低 1 小时',
      scope: 'all',
      rating: 4.8,
      reviewCount: 23,
      availabilityLabel: '空闲中',
      twinBindNote: 'B 栋 3 层仪器区',
      qualificationFiles: [{ id: 'qf-flow-1', name: '设备校准证书.pdf' }],
      needPlatformReview: false,
      limitConcurrency: true,
      auditLog: [
        { id: 'al-flow-1', at: '2025-05-08 09:00', actor: '周工', action: 'draft_save', label: '暂存草稿', detail: '' },
        { id: 'al-flow-2', at: '2025-05-09 14:20', actor: '周工', action: 'submit_review', label: '提交审核', detail: '' },
        { id: 'al-flow-3', at: '2025-05-10 10:30', actor: '李运营', action: 'audit_pass', label: '审核通过', detail: '符合要求，同意准入' },
        { id: 'al-flow-4', at: '2025-05-10 11:00', actor: '李运营', action: 'list', label: '上架', detail: '开放预约' },
      ],
    },
    {
      id: 'res-seq',
      name: '基因测序服务',
      level1: '产业联动',
      level2: 'CRO',
      providerName: '某某测序公司',
      status: 'pending_review',
      location: '—',
      intro: '全外显子与转录组测序服务。',
      hours: '工作日接单，周期 5–10 个工作日',
      contactName: '商务',
      phone: '400-000-8899',
      capability: '建库 + 测序 + 基础生信报告。',
      feeMode: 'negotiate',
      remark: '按样本复杂度报价',
      scope: 'all',
      rating: 4.5,
      reviewCount: 8,
      availabilityLabel: '需审核',
      auditLog: [
        { id: 'al-seq-1', at: '2025-05-11 16:00', actor: '商务', action: 'submit_review', label: '提交审核', detail: '' },
      ],
    },
    {
      id: 'res-lab-a',
      name: '共享实验室 A',
      level1: '载体孵化（空间）',
      level2: '共享实验室',
      providerName: '园区',
      status: 'listed',
      location: 'B201',
      intro: '细胞培养 + 基础成像一体化共享空间。',
      hours: '周一至周六 8:30-20:00',
      contactName: '前台',
      phone: '021-88880001',
      capability: '生物安全二级，含离心、培养箱、倒置显微镜。',
      feeMode: 'hourly',
      priceAmount: 150,
      priceUnit: '元/小时',
      scope: 'physical_only',
      rating: 4.6,
      reviewCount: 41,
      availabilityLabel: '占用中',
      twinBindNote: 'B 栋 2 层共享区',
    },
    {
      id: 'res-academician',
      name: '院士专家咨询',
      level1: '资源共享',
      level2: '专家',
      providerName: '产业研究院',
      status: 'listed',
      location: '会议中心',
      intro: '一对一战略与技术路线咨询。',
      hours: '预约制',
      contactName: '秘书处',
      phone: '021-66660000',
      capability: '新药立项、临床路径与园区资源对接。',
      feeMode: 'hourly',
      priceAmount: 2000,
      priceUnit: '元/小时',
      scope: 'whitelist',
      scopeWhitelistNote: '战略伙伴项目（演示）',
      rating: 5,
      reviewCount: 12,
      availabilityLabel: '可预约',
    },
    {
      id: 'res-ai',
      name: 'AI 辅助靶点挖掘',
      level1: '资源共享',
      level2: '技术服务',
      providerName: '园区 AI 中台',
      status: 'draft',
      location: '线上',
      intro: '基于公开文献与内部知识库的靶点优先级排序（演示）。',
      hours: '7×24 提交任务',
      contactName: '中台',
      phone: '021-9000',
      capability: '文献挖掘、知识图谱、优先级评分。',
      feeMode: 'free',
      scope: 'all',
      rating: 4.2,
      reviewCount: 6,
      availabilityLabel: '草稿',
      qualificationFiles: [],
      auditLog: [],
    },
    {
      id: 'res-ready',
      name: '高通量药物筛选平台',
      level1: '资源共享',
      level2: '设备',
      providerName: '园区公共实验平台',
      status: 'pending_listing',
      location: '—',
      intro: '自动化液体处理 + 读板，适用于高通量初筛。',
      hours: '预约制',
      contactName: '王工',
      phone: '021-7000',
      capability: '支持 384 孔板；需提前预约培训。',
      feeMode: 'per_project',
      priceAmount: 5000,
      priceUnit: '元/项目起',
      remark: '复杂面板另议',
      scope: 'all',
      rating: 0,
      reviewCount: 0,
      availabilityLabel: '已准入·待上架',
      qualificationFiles: [{ id: 'qf-ready-1', name: '平台验收单.pdf' }],
      needPlatformReview: true,
      limitConcurrency: true,
      auditLog: [
        { id: 'al-ready-1', at: '2025-05-08 10:00', actor: '王工', action: 'submit_review', label: '提交审核', detail: '' },
        {
          id: 'al-ready-2',
          at: '2025-05-08 15:30',
          actor: '李运营',
          action: 'audit_pass',
          label: '审核通过',
          detail: '设备与环境符合要求，准予上架',
        },
      ],
    },
    {
      id: 'res-pcr-old',
      name: '旧款PCR仪',
      level1: '资源共享',
      level2: '设备',
      providerName: '园区公共实验平台',
      status: 'listed',
      location: 'B102',
      intro: '常规 PCR 扩增（演示：低效资源）。',
      hours: '工作日',
      contactName: '周工',
      phone: '021-12345678',
      capability: '96 孔板扩增。',
      feeMode: 'hourly',
      priceAmount: 30,
      priceUnit: '元/小时',
      scope: 'all',
      rating: 3.8,
      reviewCount: 9,
      availabilityLabel: '空闲中',
    },
    {
      id: 'res-sample',
      name: '样本库A',
      level1: '资源共享',
      level2: '保藏与样本',
      providerName: '园区公共实验平台',
      status: 'listed',
      location: '冷库区',
      intro: '超低温样本存储（演示：近30天低申请）。',
      hours: '预约存取',
      contactName: '库管',
      phone: '021-7001',
      capability: '-80℃ / 液氮分区。',
      feeMode: 'per_use',
      priceAmount: 50,
      priceUnit: '元/次',
      scope: 'all',
      rating: 4.1,
      reviewCount: 4,
      availabilityLabel: '空闲中',
    },
    {
      id: 'res-scrna',
      name: '单细胞测序仪',
      level1: '资源共享',
      level2: '设备',
      providerName: '园区公共实验平台',
      status: 'listed',
      location: 'B305',
      intro: '10x 兼容文库上机（演示：高需求排队）。',
      hours: '周一至周六',
      contactName: '测序组',
      phone: '021-7002',
      capability: '单细胞转录组上机与质控。',
      feeMode: 'per_use',
      priceAmount: 1200,
      priceUnit: '元/ lane',
      scope: 'all',
      rating: 4.7,
      reviewCount: 18,
      availabilityLabel: '排队中',
      limitConcurrency: true,
    },
    {
      id: 'res-cro-beta',
      name: '毒理毒代一体化服务',
      level1: '产业联动',
      level2: 'CRO',
      providerName: 'Beta CRO公司',
      status: 'listed',
      location: '—',
      intro: '啮齿类毒理与毒代（演示：满意度偏低）。',
      hours: '按项目排期',
      contactName: 'PM',
      phone: '400-222-0001',
      capability: 'GLP 毒理报告。',
      feeMode: 'negotiate',
      scope: 'all',
      rating: 3.1,
      reviewCount: 14,
      availabilityLabel: '可接单',
    },
    {
      id: 'res-animal',
      name: '实验动物房',
      level1: '载体孵化（空间）',
      level2: '动物设施',
      providerName: '园区',
      status: 'listed',
      location: '动物楼',
      intro: 'SPF 动物饲养与操作（演示：供需缺口提示）。',
      hours: '预约制',
      contactName: '兽医',
      phone: '021-7003',
      capability: '小鼠/大鼠常规实验。',
      feeMode: 'hourly',
      priceAmount: 80,
      priceUnit: '元/笼位/天',
      scope: 'physical_only',
      rating: 4.4,
      reviewCount: 7,
      availabilityLabel: '紧张',
    },
    {
      id: 'res-seq-rush',
      name: '测序加急通道',
      level1: '产业联动',
      level2: 'CRO',
      providerName: '某某测序公司',
      status: 'maintenance',
      location: '—',
      intro: '加急文库插队通道（演示：维护中）。',
      hours: '暂停',
      contactName: '售后',
      phone: '400-000-8899',
      capability: '48h 交付（维护暂停）。',
      feeMode: 'negotiate',
      scope: 'all',
      rating: 4.0,
      reviewCount: 5,
      availabilityLabel: '维护中',
      auditLog: [
        { id: 'al-rush-1', at: '2025-05-16 09:00', actor: '系统', action: 'status_maintenance', label: '状态变更为「maintenance」', detail: '光路校准' },
      ],
    },
    {
      id: 'res-flow-flag',
      name: '流式细胞仪（投诉跟踪）',
      level1: '资源共享',
      level2: '设备',
      providerName: '园区公共实验平台',
      status: 'anomaly',
      location: 'B301',
      intro: '与 res-flow 同位演示：异常标记样本。',
      hours: '暂停预约',
      contactName: '周工',
      phone: '021-12345678',
      capability: '演示用异常资源。',
      feeMode: 'hourly',
      priceAmount: 200,
      priceUnit: '元/小时',
      scope: 'all',
      rating: 4.2,
      reviewCount: 30,
      availabilityLabel: '异常标记',
      auditLog: [
        { id: 'al-ff-1', at: '2025-05-17 11:00', actor: '李运营', action: 'status_anomaly', label: '状态变更为「anomaly」', detail: '投诉集中复核' },
      ],
    },
  ]
}

function boardDemoApplications(): ResApplication[] {
  const targets = [
    { id: 'res-flow', name: '流式细胞仪' },
    { id: 'res-academician', name: '院士专家咨询' },
    { id: 'res-lab-a', name: '共享实验室 A' },
    { id: 'res-seq', name: '基因测序服务' },
    { id: 'res-scrna', name: '单细胞测序仪' },
  ]
  const out: ResApplication[] = []
  for (let i = 0; i < 52; i++) {
    const t = targets[i % targets.length]
    const day = (i % 17) + 1
    out.push({
      id: `a-board-${i}`,
      code: `R2025${String(300 + i).padStart(3, '0')}`,
      resourceId: t.id,
      resourceName: t.name,
      applicantKey: i % 2 === 0 ? DEMO_APPLICANT_KEYS.gene : DEMO_APPLICANT_KEYS.aiDrug,
      applicantLabel: i % 2 === 0 ? '基因治疗项目' : 'AI 新药筛选平台',
      slot: `05-${String(day).padStart(2, '0')} 10:00`,
      status: i % 5 === 0 ? 'pending_confirm' : i % 5 === 1 ? 'approved' : 'completed',
      createdAt: `2025-05-${String(day).padStart(2, '0')} ${String(8 + (i % 10)).padStart(2, '0')}:15`,
    })
  }
  return out
}

export function initialApplications(): ResApplication[] {
  return [
    {
      id: 'a1',
      code: 'R2025001',
      resourceId: 'res-flow',
      resourceName: '流式细胞仪',
      applicantKey: DEMO_APPLICANT_KEYS.gene,
      applicantLabel: '基因治疗项目',
      slot: '05-20 09:00-11:00',
      status: 'pending_confirm',
      createdAt: '2025-05-15 16:20',
    },
    {
      id: 'a2',
      code: 'R2025002',
      resourceId: 'res-academician',
      resourceName: '院士专家咨询',
      applicantKey: DEMO_APPLICANT_KEYS.aiDrug,
      applicantLabel: 'AI 新药筛选平台',
      slot: '05-22 14:00-15:00',
      status: 'approved',
      createdAt: '2025-05-14 10:00',
    },
    {
      id: 'a3',
      code: 'R2025003',
      resourceId: 'res-seq',
      resourceName: '基因测序服务',
      applicantKey: DEMO_APPLICANT_KEYS.gene,
      applicantLabel: '基因治疗项目',
      slot: '05-25 全天',
      status: 'in_progress',
      createdAt: '2025-05-12 09:30',
    },
    ...boardDemoApplications(),
  ]
}

function seqCompanyDemoOrders(): ResUsageOrder[] {
  const out: ResUsageOrder[] = []
  for (let i = 0; i < 9; i++) {
    out.push({
      id: `u-seq-good-${i}`,
      code: `U2025${String(40 + i).padStart(3, '0')}`,
      resourceId: 'res-seq',
      resourceName: '基因测序服务',
      providerName: '某某测序公司',
      applicantKey: DEMO_APPLICANT_KEYS.gene,
      applicantLabel: '基因治疗项目',
      slot: '05-01 起',
      totalFeeLabel: '按合同',
      status: 'completed',
      createdAt: `2025-05-${String(1 + (i % 9)).padStart(2, '0')} 10:00`,
      timeline: [{ id: `sg-${i}`, at: `2025-05-${String(1 + (i % 9)).padStart(2, '0')} 18:00`, text: '评价已提交' }],
      resultFiles: [],
      applicantReviewStars: 5,
      applicantReviewText: '交付稳定（演示）。',
    })
  }
  return out
}

function boardDemoUsageOrders(): ResUsageOrder[] {
  return [
    {
      id: 'u-cro-seq',
      code: 'U2025025',
      resourceId: 'res-seq',
      resourceName: '基因测序服务',
      providerName: '某某测序公司',
      applicantKey: DEMO_APPLICANT_KEYS.gene,
      applicantLabel: '基因治疗项目',
      slot: '05-10 起',
      totalFeeLabel: '按合同',
      status: 'completed',
      createdAt: '2025-05-10 11:00',
      timeline: [
        { id: 's1', at: '2025-05-10 11:00', text: '下单' },
        { id: 's2', at: '2025-05-12 09:00', text: '交付延期提醒（第1次）' },
        { id: 's3', at: '2025-05-14 18:00', text: '交付延期提醒（第2次）' },
        { id: 's4', at: '2025-05-16 10:00', text: '报告交付' },
        { id: 's5', at: '2025-05-16 11:00', text: '评价已提交' },
      ],
      resultFiles: [{ name: '测序报告-外显子.pdf' }],
      applicantReviewStars: 4,
      applicantReviewText: '质量尚可，周期略慢。',
    },
    {
      id: 'u-cro-beta',
      code: 'U2025026',
      resourceId: 'res-cro-beta',
      resourceName: '毒理毒代一体化服务',
      providerName: 'Beta CRO公司',
      applicantKey: DEMO_APPLICANT_KEYS.aiDrug,
      applicantLabel: 'AI 新药筛选平台',
      slot: '04-20 起',
      totalFeeLabel: '议价',
      status: 'completed',
      createdAt: '2025-05-02 09:00',
      timeline: [
        { id: 'b1', at: '2025-05-02 09:00', text: '合同确认' },
        { id: 'b2', at: '2025-05-08 17:00', text: '阶段报告提交' },
        { id: 'b3', at: '2025-05-09 10:00', text: '项目方评价已提交' },
      ],
      resultFiles: [{ name: '毒理摘要.pdf' }],
      applicantReviewStars: 2,
      applicantReviewText: '沟通滞后，报告需返工。',
    },
    {
      id: 'u-cro-beta2',
      code: 'U2025027',
      resourceId: 'res-cro-beta',
      resourceName: '毒理毒代一体化服务',
      providerName: 'Beta CRO公司',
      applicantKey: DEMO_APPLICANT_KEYS.gene,
      applicantLabel: '基因治疗项目',
      slot: '04-28 起',
      totalFeeLabel: '议价',
      status: 'completed',
      createdAt: '2025-05-06 14:00',
      timeline: [{ id: 'b21', at: '2025-05-06 14:00', text: '完成' }],
      resultFiles: [],
      applicantReviewStars: 3,
      applicantReviewText: '一般。',
    },
    {
      id: 'u-lab',
      code: 'U2025028',
      resourceId: 'res-lab-a',
      resourceName: '共享实验室 A',
      providerName: '园区',
      applicantKey: DEMO_APPLICANT_KEYS.gene,
      applicantLabel: '基因治疗项目',
      slot: '05-18 08:00-12:00',
      totalFeeLabel: '600 元',
      status: 'completed',
      createdAt: '2025-05-18 08:05',
      timeline: [{ id: 'l1', at: '2025-05-18 12:30', text: '使用完成 · 评价已提交' }],
      resultFiles: [],
      applicantReviewStars: 5,
      applicantReviewText: '环境整洁。',
    },
  ]
}

export function initialUsageOrders(): ResUsageOrder[] {
  return [
    {
      id: 'u1',
      code: 'U2025001',
      resourceId: 'res-flow',
      resourceName: '流式细胞仪',
      providerName: '园区公共实验平台',
      applicantKey: DEMO_APPLICANT_KEYS.gene,
      applicantLabel: '基因治疗项目',
      slot: '05-20 09:00-11:00',
      totalFeeLabel: '400 元',
      status: 'in_progress',
      createdAt: '2025-05-15 16:25',
      timeline: [
        { id: 'e1', at: '2025-05-15 16:25', text: '申请已提交，待提供方确认' },
        { id: 'e2', at: '2025-05-15 17:00', text: '提供方已确认 · 已通过' },
        { id: 'e3', at: '2025-05-20 09:15', text: '项目方签到' },
      ],
      resultFiles: [],
    },
    {
      id: 'u2',
      code: 'U2025002',
      resourceId: 'res-academician',
      resourceName: '院士专家咨询',
      providerName: '产业研究院',
      applicantKey: DEMO_APPLICANT_KEYS.aiDrug,
      applicantLabel: 'AI 新药筛选平台',
      slot: '05-22 14:00-15:00',
      totalFeeLabel: '2000 元',
      status: 'completed',
      createdAt: '2025-05-14 10:05',
      timeline: [
        { id: 'e1', at: '2025-05-14 10:05', text: '申请提交' },
        { id: 'e2', at: '2025-05-14 11:00', text: '提供方确认' },
        { id: 'e3', at: '2025-05-22 15:10', text: '项目方确认完成（待评价）' },
        { id: 'e4', at: '2025-05-22 16:00', text: '项目方评价已提交' },
      ],
      resultFiles: [{ name: '会议纪要-院士咨询.pdf' }],
      applicantReviewStars: 5,
      applicantReviewText: '收获很大，路径清晰。',
    },
    ...boardDemoUsageOrders(),
    ...seqCompanyDemoOrders(),
  ]
}

export function reviewsForResource(resourceId: string): ResReview[] {
  if (resourceId === 'res-flow') {
    return [
      { id: 'rv1', at: '2025-05-10', author: '李**', stars: 5, text: '设备很新，操作员专业，推荐。' },
      { id: 'rv2', at: '2025-04-28', author: '王**', stars: 4, text: '预约略紧，总体满意。' },
    ]
  }
  return [{ id: 'rvx', at: '2025-05-01', author: '用户', stars: 5, text: '服务到位（演示）。' }]
}
